// Mock data for Harem Altın app

export const mockGoldPrices = [
  { id: 1, name: 'HAS ALTIN', nameEn: 'PURE GOLD', buy: 5807.50, sell: 5858.70, change: 0.74, unit: 'TRY' },
  { id: 2, name: 'ONS', nameEn: 'OUNCE', buy: 4239.5, sell: 4239.9, change: 0.53, unit: 'TRY' },
  { id: 3, name: 'ÇEYREK ALTIN', nameEn: 'QUARTER GOLD', buy: 2389.0, sell: 2398.0, change: 0.68, unit: 'TRY' },
  { id: 4, name: 'YARIM ALTIN', nameEn: 'HALF GOLD', buy: 4779.0, sell: 4796.0, change: 0.72, unit: 'TRY' },
  { id: 5, name: 'TAM ALTIN', nameEn: 'FULL GOLD', buy: 9558.0, sell: 9592.0, change: 0.75, unit: 'TRY' },
  { id: 6, name: '22 AYAR', nameEn: '22 CARAT', buy: 5282.82, sell: 5545.77, change: 4.83, unit: 'TRY' },
  { id: 7, name: 'GRAM ALTIN', nameEn: 'GRAM GOLD', buy: 5778.46, sell: 5876.28, change: 1.55, unit: 'TRY' },
  { id: 8, name: 'ALTIN GÜMÜŞ', nameEn: 'GOLD SILVER', buy: 70.66, sell: 73.63, change: 0.59, unit: 'TRY' },
  { id: 9, name: 'REŞAT ALTIN', nameEn: 'RESAT GOLD', buy: 9872.0, sell: 9912.0, change: 0.82, unit: 'TRY' },
  { id: 10, name: 'ATA ALTIN', nameEn: 'ATA GOLD', buy: 9612.0, sell: 9652.0, change: 0.78, unit: 'TRY' }
];

export const mockCurrencies = [
  { id: 1, name: 'USD', nameEn: 'USD', buy: 34.125, sell: 34.225, change: 0.55, symbol: '$', unit: 'TRY' },
  { id: 2, name: 'EUR', nameEn: 'EUR', buy: 35.890, sell: 36.050, change: 0.68, symbol: '€', unit: 'TRY' },
  { id: 3, name: 'GBP', nameEn: 'GBP', buy: 43.250, sell: 43.450, change: 0.42, symbol: '£', unit: 'TRY' },
  { id: 4, name: 'CHF', nameEn: 'CHF', buy: 38.650, sell: 38.850, change: 0.38, symbol: 'Fr', unit: 'TRY' },
  { id: 5, name: 'AUD', nameEn: 'AUD', buy: 22.150, sell: 22.350, change: 0.25, symbol: '$', unit: 'TRY' },
  { id: 6, name: 'CAD', nameEn: 'CAD', buy: 24.050, sell: 24.250, change: 0.31, symbol: '$', unit: 'TRY' },
  { id: 7, name: 'SAR', nameEn: 'SAR', buy: 9.100, sell: 9.200, change: 0.18, symbol: '﷼', unit: 'TRY' },
  { id: 8, name: 'JPY', nameEn: 'JPY', buy: 0.226, sell: 0.230, change: 0.22, symbol: '¥', unit: 'TRY' },
  { id: 9, name: 'KWD', nameEn: 'KWD', buy: 111.250, sell: 112.150, change: 0.45, symbol: 'KD', unit: 'TRY' },
  { id: 10, name: 'USD/KG', nameEn: 'USD/KG', buy: 137.020, sell: 137.520, change: 0.55, symbol: '$', unit: 'TRY' },
  { id: 11, name: 'EUR/KG', nameEn: 'EUR/KG', buy: 118.090, sell: 118.750, change: 0.68, symbol: '€', unit: 'TRY' }
];

export const mockPortfolio = [
  { id: 1, type: 'gold', name: 'ÇEYREK ALTIN', nameEn: 'QUARTER GOLD', quantity: 10, buyPrice: 2350.0, currentPrice: 2398.0 },
  { id: 2, type: 'gold', name: 'GRAM ALTIN', nameEn: 'GRAM GOLD', quantity: 50, buyPrice: 5650.0, currentPrice: 5876.28 },
  { id: 3, type: 'currency', name: 'USD', nameEn: 'USD', quantity: 1000, buyPrice: 33.850, currentPrice: 34.225 },
  { id: 4, type: 'currency', name: 'EUR', nameEn: 'EUR', quantity: 500, buyPrice: 35.250, currentPrice: 36.050 }
];

export const mockAlerts = [
  { id: 1, itemName: 'GRAM ALTIN', itemNameEn: 'GRAM GOLD', targetPrice: 6000, currentPrice: 5876.28, condition: 'above', active: true },
  { id: 2, itemName: 'USD', itemNameEn: 'USD', targetPrice: 34.00, currentPrice: 34.225, condition: 'below', active: true },
  { id: 3, itemName: 'EUR', itemNameEn: 'EUR', targetPrice: 37.00, currentPrice: 36.050, condition: 'above', active: false }
];

export const translations = {
  tr: {
    appName: 'Berkay Altın',
    home: 'Ana Sayfa',
    converter: 'Çevirici',
    portfolio: 'Portföy',
    alerts: 'Alarmlar',
    goldPrices: 'ALTIN FİYATLARI',
    currencyRates: 'DÖVİZ KURLARI',
    buy: 'Alış',
    sell: 'Satış',
    change: 'Değişim',
    converter_title: 'ALTIN ÇEVİRİCİ',
    converter_subtitle: '(Bilgi içindir)',
    amount: 'Miktar',
    from: 'Kaynak',
    to: 'Hedef',
    result: 'Sonuç',
    calculate: 'Hesapla',
    portfolio_title: 'PORTFÖY YÖNETİMİ',
    portfolio_empty: 'Portföyünüz boş',
    add_item: 'Ürün Ekle',
    quantity: 'Adet',
    buyPrice: 'Alış Fiyatı',
    currentPrice: 'Güncel Fiyat',
    profit_loss: 'Kar/Zarar',
    total: 'Toplam',
    alerts_title: 'FİYAT ALARMLARI',
    alerts_empty: 'Alarm bulunmuyor',
    add_alert: 'Alarm Ekle',
    target_price: 'Hedef Fiyat',
    condition: 'Koşul',
    above: 'Üstüne Çıkarsa',
    below: 'Altına Düşerse',
    active: 'Aktif',
    inactive: 'Pasif',
    delete: 'Sil',
    edit: 'Düzenle',
    save: 'Kaydet',
    cancel: 'İptal',
    search: 'Ara...',
    selectItem: 'Ürün Seçin',
    selectType: 'Tür Seçin',
    gold: 'Altın',
    currency: 'Döviz'
  },
  en: {
    appName: 'Harem Gold',
    home: 'Home',
    converter: 'Converter',
    portfolio: 'Portfolio',
    alerts: 'Alerts',
    goldPrices: 'GOLD PRICES',
    currencyRates: 'CURRENCY RATES',
    buy: 'Buy',
    sell: 'Sell',
    change: 'Change',
    converter_title: 'GOLD CONVERTER',
    converter_subtitle: '(For information)',
    amount: 'Amount',
    from: 'From',
    to: 'To',
    result: 'Result',
    calculate: 'Calculate',
    portfolio_title: 'PORTFOLIO MANAGEMENT',
    portfolio_empty: 'Your portfolio is empty',
    add_item: 'Add Item',
    quantity: 'Quantity',
    buyPrice: 'Buy Price',
    currentPrice: 'Current Price',
    profit_loss: 'Profit/Loss',
    total: 'Total',
    alerts_title: 'PRICE ALERTS',
    alerts_empty: 'No alerts found',
    add_alert: 'Add Alert',
    target_price: 'Target Price',
    condition: 'Condition',
    above: 'Goes Above',
    below: 'Goes Below',
    active: 'Active',
    inactive: 'Inactive',
    delete: 'Delete',
    edit: 'Edit',
    save: 'Save',
    cancel: 'Cancel',
    search: 'Search...',
    selectItem: 'Select Item',
    selectType: 'Select Type',
    gold: 'Gold',
    currency: 'Currency'
  }
};